// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnakvmtdzkmklwkpsasa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRuYWt2bXRkemtta2x3a3BzYXNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3MzMxMTIsImV4cCI6MjA1ODMwOTExMn0._I-wHdVnCej7QBNH84n132JcX5KubH_8gsmsdgjcCtA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);